version: '2'

services:
  app:
    build: .
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_INDEX_PREFIX: "meinms-"

networks:
  default:
    external:
      name: familiendashboard_default
